CREATE DATABASE hospital_lab;
USE hospital_lab;

CREATE TABLE patients (
patient_id INT PRIMARY KEY,
patient_name VARCHAR(100),
age INT,
city VARCHAR(50)
);

INSERT INTO patients VALUES
(1, 'Rohan Das', 34, 'Hyderabad'),
(2, 'Meena Iyer', 46, 'Chennai'),
(3, 'Kabir Khan', 29, 'Hyderabad'),
(4, 'Lakshmi Rao', 61, 'Bangalore'),
(5, 'John Mathew', 38, 'Mumbai'),
(6, 'Ayesha Ali', 25, NULL),
(7, 'Naveen Reddy', 52, 'Pune');

CREATE TABLE doctors (
doctor_id INT PRIMARY KEY,
doctor_name VARCHAR(100),
specialization VARCHAR(50),
consultation_fee DECIMAL(10,2)
);

INSERT INTO doctors VALUES
(101, 'Dr. Sharma', 'Cardiology', 1200),
(102, 'Dr. Farah', 'Dermatology', 800),
(103, 'Dr. Joseph', 'Orthopedics', 1000),
(104, 'Dr. Mehta', 'General Medicine', 600),
(105, 'Dr. Sana', 'Neurology', 1500),
(106, 'Dr. Rao', 'Pediatrics', 700);

CREATE TABLE appointments (
appointment_id INT PRIMARY KEY,
patient_id INT,
doctor_id INT,
appointment_date DATE,
status VARCHAR(30)
);
INSERT INTO appointments VALUES
(1001, 1, 101, '2026-10-01', 'Completed'),
(1002, 2, 104, '2026-10-01', 'Completed'),
(1003, 3, 102, '2026-10-02', 'Cancelled'),
(1004, 1, 105, '2026-10-03', 'Completed'),
(1005, 4, 101, '2026-10-03', 'Scheduled'),
(1006, 5, 103, '2026-10-04', 'Completed'),
(1007, 3, 104, '2026-10-04', 'Completed'),
(1008, NULL, 102, '2026-10-05', 'Scheduled'),
(1009, 20, 103, '2026-10-05', 'Completed'),
(1010, 2, NULL, '2026-10-06', 'Scheduled');

-- 1. Display appointment ID, patient name, doctor name and appointment date.
select appointment_id,patient_name, doctor_name,appointment_date 
from appointments a 
join patients p on a.patient_id=p.patient_id
join doctors d on a.doctor_id=d.doctor_id;

-- 2. Show the doctor and specialization for every completed appointment.
select doctor_name,specialization
from doctors d
join appointments a on a.doctor_id=d.doctor_id
where status='Completed';

-- 3. Find all appointments made by patients from Hyderabad.
select * from patients p
join appointments a on a.patient_id=p.patient_id
where city = 'Hyderabad';

-- 4. Display every patient and their appointment details. Patients who have never booked an
-- appointment must also appear.
select p.patient_id,p.patient_name,a.appointment_id,a.doctor_id,a.appointment_date,a.status
from patients p
left join appointments a On p.patient_id=a.patient_id;

-- 5. Find patients who have never booked an appointment
select p.patient_id,p.patient_name 
from patients p
left join appointments a on p.patient_id=a.patient_id
where a.appointment_id is Null;

-- 6. Display every doctor and appointments handled by them including doctors with no appointments
select d.doctor_id,d.doctor_name,d.specialization,a.appointment_id,a.patient_id,a.appointment_date,a.status
from doctors d
left join appointments a on d.doctor_id = a.doctor_id;

-- 7. Find doctors who currently have no appointments
select d.doctor_id,d.doctor_name,d.specialization
from doctors d 
left join appointments a on d.doctor_id =a.doctor_id
where a.appointment_id is Null;

-- 8. Identify appointment records for which a valid patient cannot be found
select a.* from appointments a 
left join patients p on a.patient_id = p.patient_id
where p.patient_id is null;

-- 9. Identify appointment records for which a doctor has not been assigned
select * from appointments where doctor_id is null;

-- 10. Display Patient Name, Doctor Name, Specialization, Consultation Fee, and Status for all valid appointments
select p.patient_name,d.doctor_name,d.specialization,d.consultation_fee,a.status
from appointments a 
join patients p on a.patient_id = p.patient_id
join doctors d on a.doctor_id = d.doctor_id;

-- 11. Find the number of appointments handled by each doctor
select d.doctor_id,d.doctor_name, count(a.appointment_id) as total_appointments
from doctors d 
left join appointments a on d.doctor_id =a.doctor_id
group by d.doctor_id,d.doctor_name;

-- 12. Find the total consultation value generated by each doctor based on completed appointments only
select d.doctor_id,d.doctor_name,sum(d.consultation_fee) as total_value
from doctors d 
join appointments a on d.doctor_id=a.doctor_id
where a.status='Completed'
group by d.doctor_id, d.doctor_name;

-- 13. Find doctors who have handled more than one appointment
select d.doctor_id,d.doctor_name,count(a.appointment_id) as appointment_count
from doctors d 
join appointments a on d.doctor_id = a.doctor_id
group by d.doctor_id,d.doctor_name
having count(a.appointment_id)>1;

-- 14. Find the specialization generating the highest total consultation value
select d.specialization, sum(d.consultation_fee) as total_value
from doctors d 
join appointments a on d.doctor_id=a.doctor_id
where a.status='Completed'
group by d.specialization
order by total_value desc
limit 1;

-- 15. Display each patient and the number of appointments they have booked including zero appointments
select p.patient_id,p.patient_name,count(a.appointment_id) as appointments_booked
from patients p 
left join appointments a on p.patient_id = a.patient_id
group by p.patient_id,p.patient_name;

-- 16. Find patients who have consulted more than one doctor
select p.patient_id,p.patient_name, count(distinct a.doctor_id) as distinct_doctors_consulted
from patients p 
join appointments a on p.patient_id =a.patient_id
where a.doctor_id is not null
group by p.patient_id,p.patient_name
having count(distinct a.doctor_id)>1;

-- 17. Find patients who have visited a Cardiology doctor
select distinct p.patient_id,p.patient_name from patients p 
join appointments a on p.patient_id= a.patient_id
join doctors d on a.doctor_id = d.doctor_id
where d.specialization = 'Cardiology';

-- 18. Display appointments where the consultation fee is greater than ₹900
select a.appointment_id,a.patient_id,d.doctor_name,d.consultation_fee,a.status
from appointments a 
join doctors d on a.doctor_id=d.doctor_id
where d.consultation_fee>900;

-- 19. Find the average consultation fee of doctors involved in completed appointments
select avg(d.consultation_fee) as avg_fee
from appointments a 
join doctors d on a.doctor_id=d.doctor_id
where a.status='Completed';

-- 20. Display the doctor who has handled the highest number of completed appointments
select d.doctor_id,d.doctor_name,count(a.appointment_id) as completed_count
from doctors d 
join appointments a on d.doctor_id = a.doctor_id
where a.status ='Completed'
group by d.doctor_id,d.doctor_name
order by completed_count desc
limit 1;