-- Assessment 2 — Airline Booking & Employee Operations

CREATE DATABASE airline_assessment;
USE airline_assessment;

CREATE TABLE flights (
flight_id INT PRIMARY KEY,
airline VARCHAR(50),
source_city VARCHAR(50),
destination_city VARCHAR(50),
ticket_price DECIMAL(10,2)
);
INSERT INTO flights VALUES
(201, 'SkyJet', 'Hyderabad', 'Delhi', 6500),
(202, 'AirWorld', 'Mumbai', 'Bangalore', 7200),
(203, 'SkyJet', 'Delhi', 'Mumbai', 5800),
(204, 'FlyHigh', 'Hyderabad', 'Dubai', 18000),
(205, 'AirWorld', 'Bangalore', 'Delhi', 6900),
(206, 'FlyHigh', 'Mumbai', 'Singapore', 22000),
(207, 'SkyJet', 'Hyderabad', 'Mumbai', 5200);

CREATE TABLE passengers (
passenger_id INT PRIMARY KEY,
passenger_name VARCHAR(100),
city VARCHAR(50),
email VARCHAR(100)
);
INSERT INTO passengers VALUES
(1, 'Aman Verma', 'Hyderabad', ' AMAN@MAIL.COM '),
(2, 'Sara Ali', 'Mumbai', 'sara@gmail.com'),
(3, 'Rakesh Rao', 'Delhi', ''),
(4, 'Meena Shah', 'Bangalore', 'MEENA@YAHOO.COM'),
(5, 'Farah Khan', 'Hyderabad', NULL),
(6, 'John Mathew', 'Pune', 'john@gmail.com'),
(7, 'Priya Das', NULL, 'priya@mail.com');

CREATE TABLE bookings (
booking_id INT PRIMARY KEY,
passenger_id INT,
flight_id INT,
booking_date DATE,
seats INT,
status VARCHAR(20)
);
INSERT INTO bookings VALUES
(1001, 1, 201, '2026-06-01', 1, 'Confirmed'),
(1002, 2, 202, '2026-06-02', 2, 'Confirmed'),
(1003, 1, 204, '2026-06-03', 1, 'Confirmed'),
(1004, 3, 203, '2026-06-04', 1, 'Cancelled'),
(1005, 4, 205, '2026-06-05', 3, 'Confirmed'),
(1006, 5, 207, '2026-06-06', 2, 'Confirmed'),
(1007, 2, 206, '2026-06-07', 1, 'Confirmed'),
(1008, 20, 201, '2026-06-08', 1, 'Confirmed'),
(1009, 6, NULL, '2026-06-09', 2, 'Pending');

CREATE TABLE airline_staff (
employee_id INT PRIMARY KEY,
employee_name VARCHAR(100),
manager_id INT,
department VARCHAR(50),
salary DECIMAL(10,2)
);
INSERT INTO airline_staff VALUES
(1, 'Raj Kumar', NULL, 'Management', 200000),
(2, 'Meera Rao', 1, 'Operations', 140000),
(3, 'Imran Khan', 1, 'Sales', 135000),
(4, 'Aman Shah', 2, 'Operations', 90000),
(5, 'Priya Singh', 2, 'Operations', 85000),
(6, 'Rohit Das', 3, 'Sales', 75000),
(7, 'Farah Ali', 3, 'Sales', 78000),
(8, 'Vikas Rao', 4, 'Support', 60000);

-- Section A - Filtering & Manipulation

-- 1. Display flights originating from Hyderabad.
select * from flights where source_city='Hyderabad';

-- 2. Display flights priced between ₹6,000 and ₹20,000.
select * from flights where ticket_price between 6000 and 20000;

-- 3. Display international-looking routes where ticket price exceeds ₹15,000.
select * from flights where ticket_price>15000;

-- 4. Increase the ticket price of all SkyJet flights by 5%.
update flights 
set ticket_price= ticket_price*1.05
where airline='SkyJet';

-- 5. Display the three most expensive flights.
select * from flights 
order by ticket_price Desc
limit 3;

-- Section B - Aggregate / Group By / Having

-- 6. Find average ticket price by airline.
select airline,avg(ticket_price) as avg_ticket_price from flights group by airline;

-- 7. Find total number of seats booked on each flight.
select flight_id, sum(seats) as total_seats_booked
from bookings group by flight_id;

-- 8. Find airlines whose average ticket price exceeds ₹8,000.
select airline,avg(ticket_price) as avg_ticket_price
from flights
group by airline
having avg(ticket_price)>8000;

-- 9. Find total booking value per airline using:
select f.airline,sum(b.seats*f.ticket_price) as total_booking_value
from bookings b 
join flights f on b.flight_id =f.flight_id
group by f.airline;

-- Section C - Joins

-- 10. Display passenger name, airline, source, destination and booking status.
select p.passenger_name, f.airline,f.source_city,f.destination_city,b.status
from bookings b 
join passengers p on b.passenger_id = b.passenger_id
join flights f on b.flight_id=f.flight_id;

-- 11. Display all passengers including passengers who have never booked a flight.
select p.passenger_id,p.passenger_name,b.booking_id,b.status,b.flight_id
from passengers p 
left join bookings b on p.passenger_id = b.passenger_id;

-- 12. Find bookings having either: no valid passenger, or no valid flight.
select b.booking_id,b.passenger_id,b.flight_id,b.status
from bookings b 
left join passengers p on b.passenger_id = p.passenger_id
left join flights f on b.flight_id=f.flight_id
where p.passenger_id is null or f.flight_id is null;

-- Section D - Join + Aggregate

-- 13. Calculate total booking value generated by every passenger.
select p.passenger_id,p.passenger_name,sum(b.seats*f.ticket_price) as total_booking_value
from passengers p 
left join bookings b on p.passenger_id = b.passenger_id
left join flights f on b.flight_id = f.flight_id
group by p.passenger_id,p.passenger_name;

-- 14. Display passengers whose confirmed booking value exceeds ₹10,000.
select p.passenger_id,p.passenger_name,sum(b.seats*f.ticket_price) as total_booking_value
from passengers p 
left join bookings b on p.passenger_id = b.passenger_id
left join flights f on b.flight_id = f.flight_id
where b.status='Confirmed'
group by p.passenger_id,p.passenger_name
having sum(b.seats*f.ticket_price)>10000;